#!/bin/sh
# set -e

PREFIX="[Init]"
if [ "$CUSTOM_SERVER_REPO" ]; then
  [ ! "$CUSTOM_SERVER" ] && export CUSTOM_SERVER=./server.jar
  [ ! "$CUSTOM_SERVER_TAG" ] && export CUSTOM_SERVER_TAG=latest

  echo "$PREFIX Checking for server updates from $CUSTOM_SERVER_REPO"

  [ "$KEEPUP_GITHUB_AUTH_TOKEN" ] && AUTHORIZATION="--header 'authorization: Bearer $KEEPUP_GITHUB_AUTH_TOKEN'" || AUTHORIZATION=""

  GITHUB_API="https://api.github.com/repos/$CUSTOM_SERVER_REPO/releases/$CUSTOM_SERVER_TAG"
  GITHUB_RESPONSE=$(curl $AUTHORIZATION -s "$GITHUB_API")

  LATEST_RELEASE_DATE=$(echo $GITHUB_RESPONSE | jq -r '.published_at' 2>/dev/null)
  CURRENT_RELEASE_DATE=$(getfattr --only-values -n user.release-date "$CUSTOM_SERVER" 2>/dev/null)

  echo "$PREFIX Latest release date: $LATEST_RELEASE_DATE"
  echo "$PREFIX Current release date: $CURRENT_RELEASE_DATE"

  if [ "$LATEST_RELEASE_DATE" != "$CURRENT_RELEASE_DATE" ]; then
    echo "$PREFIX Downloading new release, release date: $LATEST_RELEASE_DATE"
    wget $(echo $GITHUB_RESPONSE | jq -r '.assets[] | select(.name | contains ("jar")) | .browser_download_url')\
      -q -O "$CUSTOM_SERVER"

    setfattr -n user.release-date -v "$LATEST_RELEASE_DATE" "$CUSTOM_SERVER"
    chmod +x "$CUSTOM_SERVER"
  else
    echo "$PREFIX Server is up to date"
  fi
fi
