#!/bin/bash

set -euo pipefail

usermod -u $UID minecraft
groupmod -o -g "$GID" minecraft

if [ "$UPDATE_DATA_OWNER" = "true" ]; then
  echo "[Init] Updating owner for $HOME and /configs to $UID:$GID"
  chown $UID:$GID -R $HOME
  [ -d /configs ] && chown $UID:$GID -R /configs
fi

exec setpriv --reuid $UID --regid $GID --init-groups --inh-caps=-all /scripts/rootless
