#!/bin/bash

PREFIX="[Init]"

log_error() {
  echo -e "\e[31m$PREFIX Error: $1\e[0m" >&2
  exit 1
}

log_warning() {
  echo -e "\e[33m$PREFIX Warning: $1\e[0m"
}

log_info() {
  echo "$PREFIX Info: $1"
}
