#!/bin/sh

keepupDir=$HOME/keepupDir
keepupDownloadsDir=$keepupDir/downloads
#keepupOverridesFile=$keepupDir/overrides.conf
pluginsDir=$HOME/plugins
configSource=/configs/server-config/
pluginVersionsFile=/configs/server-config/.servers/plugins.conf
inventoryFile=/configs/server-config/.servers/configs.yml
