#!/bin/sh

. /scripts/helpers
. /scripts/keepup-helpers

keepup config --source "$configSource" --dest "$HOME" --inventory "$inventoryFile" \
    --template-cache "$keepupDir/templates" "${SERVER_NAME}" || log_error "Keepup config copy failed."
