#!/bin/bash

keepupDir=$HOME/keepupDir
keepupDownloadsDir=$keepupDir/downloads
#keepupOverridesFile=$keepupDir/overrides.conf
pluginsDir=$HOME/plugins
configSource=/configs/server-config/
pluginVersionsFile=/configs/server-config/keepup/plugins.conf
inventoryFile=/configs/server-config/keepup/configs.yml
