#!/bin/sh
set -e

echo [Init] Running scripts as user: $(whoami)

. /scripts/download_server
if [ "$CONFIGS_PULL" = "true" ]; then
  . /scripts/pull_config_repos
fi
. /scripts/keepup

if [ "$DEV_REMOTE_DEBUG" = "true" ]; then
  JVM_OPTS="$JVM_OPTS -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
fi

# Accept EULA if env variable set
if [ "$EULA" = "true" ] && ! grep -q "eula=true" eula.txt; then
  echo "eula=true" > eula.txt
fi

# If /start exists
if [ -f /start ]; then
  exec /start
else
  exec java -Xms${MEMORY} -Xmx${MEMORY} $JVM_XX_OPTS $JVM_OPTS $expandedDOpts -jar "$(basename "${SERVER_JAR}")" "$@" $EXTRA_ARGS
fi
