#!/bin/sh
set -e

echo [Init] Running scripts as user: $(whoami)

. /scripts/ansible
. /scripts/keepup
. /scripts/download_server

# If /start exists
if [ -f /start ]; then
  exec /start
else
  exec java $JVM_XX_OPTS $JVM_OPTS $expandedDOpts -jar "$(basename "${CUSTOM_SERVER}")" "$@" $EXTRA_ARGS
fi
