#!/bin/sh
set -e

if [ "$ANSIBLE" = "enabled" ]; then
  if [ "$ANSIBLE_PULL" = "enabled" ]; then
    echo "Pulling and running latest server config ansible playbook"

    ansible-pull -U "https://github.com/MineInAbyss/server-config.git" -d "/server-config" --checkout "${ANSIBLE_PULL_BRANCH:=master}" -v
  elif [ -f "/server-config/local.yml" ]; then
    echo "Running local server config ansible playbook"

    ansible-playbook /server-config/local.yml --extra-vars "server_name=$SERVER_NAME dest=/data"
  fi
else
  echo "ANSIBLE not set to 'enabled', not running playbook"
fi
