#!/bin/sh
set -e

PREFIX="[Download Server]"
if [ "$CUSTOM_SERVER_REPO" ]; then
  [ ! "$CUSTOM_SERVER" ] && export CUSTOM_SERVER=./server.jar

  echo "$PREFIX Checking for server updates from $CUSTOM_SERVER_REPO"

  export LATEST_RELEASE_DATE=$(curl -s "https://api.github.com/repos/$CUSTOM_SERVER_REPO/releases/latest" | jq -r '.published_at' 2>/dev/null)
  export CURRENT_RELEASE_DATE=$(getfattr --only-values -n user.release-date "$CUSTOM_SERVER" 2>/dev/null)

  echo "$PREFIX Latest release date: $LATEST_RELEASE_DATE"
  echo "$PREFIX Current release date: $CURRENT_RELEASE_DATE"

  if [ "$LATEST_RELEASE_DATE" != "$CURRENT_RELEASE_DATE" ]; then
    echo "$PREFIX Downloading new release, release date: $LATEST_RELEASE_DATE"
    wget $(curl -s https://api.github.com/repos/$CUSTOM_SERVER_REPO/releases/latest  | jq -r '.assets[] | select(.name | contains ("jar")) | .browser_download_url')\
      -q --show-progress -O "$CUSTOM_SERVER"

    setfattr -n user.release-date -v "$LATEST_RELEASE_DATE" "$CUSTOM_SERVER"
    chmod +x "$CUSTOM_SERVER"
  else
    echo "$PREFIX Server is up to date"
  fi
fi
