#!/bin/bash

set -e

. /scripts/dev/ansible
. /scripts/dev/keepup
. /scripts/dev/download_server

if [ "$UPDATE_DATA_OWNER" = "true" ]; then
  echo "[Init] Updating owner for /data to $UID:$GID"
  chown $UID:$GID -R /data
fi

exec /start
