#!/bin/sh
set -e

keepupDir=$HOME/keepupDir
keepupDownloadsDir=$keepupDir/downloads
#keepupOverridesFile=$keepupDir/overrides.conf
pluginsDir=$HOME/plugins
configSource=/server-config/
pluginVersionsFile=/server-config/keepup/plugins.conf
PREFIX="[Init]"
mkdir -p "$keepupDir"
mkdir -p "$keepupDownloadsDir"
mkdir -p "$pluginsDir"

if [ "$KEEPUP" = "true" ]; then
#    if [ ! -f "$keepupOverridesFile" ]; then
#      echo "Creating default keepup overrides file"
#      touch "$keepupOverridesFile"
#    fi

    if [ ! -f "$pluginVersionsFile" ]; then
          echo "$PREFIX Plugin versions file not found at $pluginVersionsFile, skipping keepup"
          return
    fi

    if [ -z "$KEEPUP_JSON_PATH" ]; then
      export KEEPUP_JSON_PATH=mineinabyss.servers.${SERVER_NAME}
    fi

  echo "$PREFIX Keepup enabled"
  keepup plugins --hide-progress-bar --ignore-similar $pluginVersionsFile $keepupDownloadsDir $pluginsDir \
    config --source $configSource --dest $HOME --inventory $keepupDir/keepup-configs.yml --template-cache $keepupDir/templates ${SERVER_NAME}
else
  echo "$PREFIX KEEPUP is not set to 'true', not running keepup"
fi
