#!/bin/sh
set -e

keepup=$HOME/keepup
keepupMia=$keepup/mineinabyss.conf
keepupDownloads=$keepup/downloads
keepupOverridesFile=$keepup/overrides.conf
paperPlugins=$HOME/plugins
pluginVersionsFile=/server-config/servers/plugin-versions.conf

mkdir -p "$keepup"
mkdir -p "$keepupDownloads"
mkdir -p "$paperPlugins"

if [ "$KEEPUP" = "enabled" ]; then
  echo "Keepup enabled"

  if  [ "$KEEPUP_ALLOW_OVERRIDES" = "true" ]; then
    if [ ! -f "$keepupOverridesFile" ]; then
      echo "Creating default keepup overrides file"
      touch "$keepupOverridesFile"
    fi

    echo "Running keepup with overrides"
    cat $keepupMia $keepupOverridesFile 2>/dev/null\
      | keepup - $keepupDownloads $paperPlugins --json-path=servers.${SERVER_NAME}
  else
    echo "Running keepup without overrides"
    keepup $pluginVersionsFile\
      $keepupDownloads $paperPlugins --json-path=servers.${SERVER_NAME}
  fi
else
  echo "KEEPUP is not set to 'enabled', not running keepup"
fi
