#!/bin/sh
set -e

keepupDir=$HOME/keepupDir
keepupDownloadsDir=$keepupDir/downloads
keepupOverridesFile=$keepupDir/overrides.conf
pluginsDir=$HOME/plugins
pluginVersionsFile=/server-config/servers/plugin-versions.conf

mkdir -p "$keepupDir"
mkdir -p "$keepupDownloadsDir"
mkdir -p "$pluginsDir"

if [ "$KEEPUP" = "true" ]; then
  echo "Keepup enabled"

  if  [ "$KEEPUP_ALLOW_OVERRIDES" = "true" ]; then
    if [ ! -f "$keepupOverridesFile" ]; then
      echo "Creating default keepup overrides file"
      touch "$keepupOverridesFile"
    fi

    if [ ! -f "$pluginVersionsFile" ]; then
          echo "Plugin versions file not found at $pluginVersionsFile, skipping keepup"
          return
    fi


    if [ -z "$KEEPUP_JSON_PATH" ]; then
      export KEEPUP_JSON_PATH=mineinabyss.servers.${SERVER_NAME}
    fi

    echo "Running keepup with overrides"
    cat $pluginVersionsFile $keepupOverridesFile 2>/dev/null\
      | keepup - $keepupDownloadsDir $pluginsDir
  else
    echo "Running keepup without overrides"
    keepup $pluginVersionsFile\
      $keepupDownloadsDir $pluginsDir
  fi
else
  echo "KEEPUP is not set to 'true', not running keepup"
fi
