name: build java
on:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - master
    paths:
      - production/**
      - development/**
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  push:
    name: "docker:java_${{ matrix.tag }}"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push prod
        uses: docker/build-push-action@v2
        with:
          context: ./production
          file: ./production/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            mineinabyss/yolks:latest

      - name: Build and push local dev
        uses: docker/build-push-action@v2
        with:
          context: ./development
          file: ./development/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            mineinabyss/papermc:latest
